### PR TITLE
Make improvements to the JavaScript-related stuff

### PR DESCRIPTION
**Pull request by smorimoto**

### CODE REVIEW

**Comment by walfie** [comment]
I'll need to check to see what Parcel does by default for ES6 classes (whether it rewrites them to be compatible with older browsers that don't support classes), but I think it looks good!

I may need to add a precommit hook for JS formatting stuff (maybe husky+prettier) so it becomes less of an issue.

FYI I am not really a frontend developer and am somewhat unfamiliar with best practices in JS and especially OCaml, so I appreciate any recommendations.

**Comment by smorimoto** [comment]
I think Percel can handle it well. Well, I'm not a front-end developer either, so I'm not sure I know much of what the best practices are, but I think it's certainly a good idea to use Prettier. (Because ocamlformat has already been introduced.)

**Comment by smorimoto** [comment]
Rebased to trigger CI.

**Comment by walfie** [comment]
ok I've checked the minified code and it seems like the current setup doesn't convert ES6 classes to older syntax. However, it's only really an issue with Internet Explorer, which is fine with me -- I can adjust the config to support older versions later if it ends up being a problem.

**Comment by smorimoto** [comment]
This seems to be the cause.
https://github.com/walfie/ac-tune-maker/blob/master/package.json#L37

**Comment by walfie** [comment]
yeah I think I added that after running into some issues with the Parcel auto-reloader, but don't remember exactly what it was

**Comment by smorimoto** [comment]
You can configure which browsers are supported by specifying a query.
https://github.com/browserslist/browserslist

**Comment by walfie** [comment]
Now I remember why I added that browserslist restriction -- it was because of Parcel's default handling of async functions causing issues. It's not needed anymore since there's no async used in the codebase, so I've removed it: https://github.com/walfie/ac-tune-maker/commit/ef724a6fcdb9b25c4cbffc463c2cb63ce3dda5c9

**Pull request merged**
